const CHAT='https://chatgpt.com/';
const TG='send-selection-to-telegram';
const sleep=m=>new Promise(r=>setTimeout(r,m));
async function defaults(){const c=await chrome.storage.local.get(['autoSend','includeSource','telegramBotToken','telegramChatId','geminiApiKey','geminiModel','enableGemini','enableChatGPT']);const d={};if(typeof c.autoSend!=='boolean')d.autoSend=true;if(typeof c.includeSource!=='boolean')d.includeSource=false;if(typeof c.telegramBotToken!=='string')d.telegramBotToken='';if(typeof c.telegramChatId!=='string')d.telegramChatId='';if(typeof c.geminiApiKey!=='string')d.geminiApiKey='';if(typeof c.geminiModel!=='string')d.geminiModel='';if(typeof c.enableGemini!=='boolean')d.enableGemini=true;if(typeof c.enableChatGPT!=='boolean')d.enableChatGPT=true;if(Object.keys(d).length)await chrome.storage.local.set(d)}
function menus(){chrome.contextMenus.removeAll(()=>{chrome.contextMenus.create({id:TG,title:'Gửi đoạn đã chọn → Telegram',contexts:['selection']})})}
chrome.runtime.onInstalled.addListener(async()=>{await defaults();menus()});chrome.runtime.onStartup.addListener(async()=>{await defaults();menus()});
const isChat=u=>/^https:\/\/(chatgpt\.com|chat\.openai\.com)(\/|$)/i.test(String(u||''));
async function waitComplete(id){try{if((await chrome.tabs.get(id)).status==='complete')return}catch(_){}await new Promise(resolve=>{let done=false;const finish=()=>{if(done)return;done=true;chrome.tabs.onUpdated.removeListener(l);clearTimeout(t);resolve()};const l=(tid,c)=>{if(tid===id&&c.status==='complete')finish()};const t=setTimeout(finish,20000);chrome.tabs.onUpdated.addListener(l)})}
async function deliverChat(prompt){const tabs=await chrome.tabs.query({});let tab=tabs.find(t=>t.active&&isChat(t.url))||tabs.find(t=>isChat(t.url));if(!tab)tab=await chrome.tabs.create({url:CHAT,active:true});else await chrome.tabs.update(tab.id,{active:true});try{await chrome.windows.update(tab.windowId,{focused:true})}catch(_){}await waitComplete(tab.id);for(let i=0;i<10;i++){try{const r=await chrome.tabs.sendMessage(tab.id,{type:'FILL_AND_SEND_CHATGPT',text:prompt,autoSend:true});if(r?.ok)return r}catch(_){}try{await chrome.scripting.executeScript({target:{tabId:tab.id},files:['chatgpt-direct.js']})}catch(_){}await sleep(700)}return{ok:false,error:'Không thể gửi prompt trực tiếp tới ChatGPT.'}}
async function gemini(prompt){const s=await chrome.storage.local.get({geminiApiKey:'',geminiModel:''});const key=s.geminiApiKey.trim(),model=s.geminiModel.trim();if(!key)throw Error('Chưa nhập Gemini API Key.');if(!model)throw Error('Chưa chọn Gemini model.');const u=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`;const r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{role:'user',parts:[{text:String(prompt).trim()}]}]})});const d=await r.json();if(!r.ok||d?.error)throw Error(d?.error?.message||`Gemini HTTP ${r.status}`);const out=(d?.candidates||[]).flatMap(c=>c?.content?.parts||[]).map(p=>p?.text||'').join('').trim();if(!out)throw Error('Gemini không trả về nội dung.');return out}
function chunks(t,n=3900){t=String(t||'').trim();const a=[];while(t.length>n){let i=t.lastIndexOf('\n',n);if(i<2000)i=t.lastIndexOf(' ',n);if(i<2000)i=n;a.push(t.slice(0,i).trim());t=t.slice(i).trim()}if(t)a.push(t);return a}
async function tg(text){const s=await chrome.storage.local.get({telegramBotToken:'',telegramChatId:''});if(!s.telegramBotToken.trim()||!s.telegramChatId.trim())throw Error('Chưa nhập Telegram Bot Token hoặc Chat ID.');for(const x of chunks(text)){const r=await fetch(`https://api.telegram.org/bot${encodeURIComponent(s.telegramBotToken.trim())}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:s.telegramChatId.trim(),text:x,disable_web_page_preview:true})});const d=await r.json();if(!r.ok||!d.ok)throw Error(d?.description||`Telegram HTTP ${r.status}`)}return{ok:true}}
async function both(text){const g=gemini(text).then(async a=>{const m=(await chrome.storage.local.get({geminiModel:''})).geminiModel;try{await tg(`✨ Gemini (${m||'model'})\n\n${a}`);return{ok:true,provider:'gemini',telegram:true}}catch(e){return{ok:true,provider:'gemini',telegram:false,error:String(e?.message||e)}}}).catch(e=>({ok:false,provider:'gemini',error:String(e?.message||e)}));const c=deliverChat(text).then(r=>({provider:'chatgpt',...r}));return Promise.all([c,g])}
async function geminiRequest(key,model){if(!key)throw Error('Chưa nhập Gemini API Key.');if(!model)throw Error('Chưa chọn Gemini model.');const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{role:'user',parts:[{text:'Trả lời ngắn gọn: Gemini API đang hoạt động tốt.'}]}]})});const d=await r.json();if(!r.ok||d?.error)throw Error(d?.error?.message||`Gemini HTTP ${r.status}`);return(d?.candidates||[]).flatMap(c=>c?.content?.parts||[]).map(p=>p?.text||'').join('').trim()}
async function listModels(key){key=String(key||'').trim();if(!key)throw Error('Chưa nhập Gemini API Key.');const out=[];let token='';const seen=new Set();for(let i=0;i<20;i++){const q=new URLSearchParams({pageSize:'100'});if(token)q.set('pageToken',token);const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models?${q}`,{headers:{'x-goog-api-key':key}});const d=await r.json();if(!r.ok||d?.error)throw Error(d?.error?.message||`Gemini ListModels HTTP ${r.status}`);for(const m of d?.models||[]){const name=String(m?.name||'').replace(/^models\//,'');const actions=Array.isArray(m?.supportedGenerationMethods)?m.supportedGenerationMethods:[];if(name&&actions.includes('generateContent'))out.push({name,displayName:String(m?.displayName||name),description:String(m?.description||''),inputTokenLimit:m?.inputTokenLimit??null,outputTokenLimit:m?.outputTokenLimit??null})}token=String(d?.nextPageToken||'');if(!token||seen.has(token))break;seen.add(token)}const unique=[...new Map(out.map(x=>[x.name,x])).values()];unique.sort((a,b)=>a.displayName.localeCompare(b.displayName));if(!unique.length)throw Error('API Key hợp lệ nhưng không có model generateContent.');return unique}
chrome.runtime.onMessage.addListener((m,s,reply)=>{if(m?.type==='ASK_CHATGPT_WEB'){both(m.text).then(r=>reply({ok:r.some(x=>x.ok!==false),results:r})).catch(e=>reply({ok:false,error:String(e?.message||e)}));return true}if(m?.type==='TEST_TELEGRAM'){tg('✅ Kết nối Telegram thành công.').then(reply).catch(e=>reply({ok:false,error:String(e?.message||e)}));return true}if(m?.type==='TEST_GEMINI'){const key=String(m.apiKey||'').trim(),model=String(m.model||'').trim();geminiRequest(key,model).then(async a=>{let sent=false,err='';try{await tg(`✨ Gemini Test (${model||'model'})\n\n${a}`);sent=true}catch(e){err=String(e?.message||e)}reply({ok:true,answer:a,telegramSent:sent,telegramError:err})}).catch(e=>reply({ok:false,error:String(e?.message||e)}));return true}if(m?.type==='SEND_CHATGPT_ANSWER'){tg('🤖 ChatGPT trả lời\n\n'+String(m.text||'')).then(reply).catch(e=>reply({ok:false,error:String(e?.message||e)}));return true}if(m?.type==='LIST_GEMINI_MODELS'){listModels(m.apiKey).then(async models=>{await chrome.storage.local.set({geminiApiKey:String(m.apiKey||'').trim()});reply({ok:true,models})}).catch(e=>reply({ok:false,error:String(e?.message||e)}));return true}});
chrome.contextMenus.onClicked.addListener((info,tab)=>{if(!info.selectionText)return;if(info.menuItemId===TG){tg(info.selectionText).catch(console.error)}});