(()=>{
if(globalThis.__RCGPT_DIRECT__)return;globalThis.__RCGPT_DIRECT__=1;
const sleep=m=>new Promise(r=>setTimeout(r,m));
const get=()=>document.querySelector('#prompt-textarea')||document.querySelector('[data-testid="composer-input"]')||document.querySelector('textarea[placeholder]')||document.querySelector('[contenteditable="true"]');
const val=e=>e?('value'in e?String(e.value||''):String(e.innerText||e.textContent||'')).trim():'';
const fire=(e,t)=>{try{e.dispatchEvent(new InputEvent('beforeinput',{bubbles:true,cancelable:true,inputType:'insertText',data:t}))}catch(_){}try{e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:t}))}catch(_){e.dispatchEvent(new Event('input',{bubbles:true}))}try{e.dispatchEvent(new Event('change',{bubbles:true}))}catch(_){}};
function fill(e,t){e.focus();if(e instanceof HTMLTextAreaElement||e instanceof HTMLInputElement){const p=e instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,s=Object.getOwnPropertyDescriptor(p,'value')?.set;if(!s)throw Error('Không có value setter');s.call(e,t);fire(e,t);return}const sel=getSelection(),r=document.createRange();r.selectNodeContents(e);sel.removeAllRanges();sel.addRange(r);try{document.execCommand('insertText',false,t)}catch(_){}if(val(e)!==t.trim()){e.replaceChildren();const p=document.createElement('p');p.textContent=t;e.appendChild(p)}fire(e,t)}
const btn=()=>[document.querySelector('[data-testid="send-button"]'),document.querySelector('button[aria-label="Send prompt"]'),document.querySelector('button[aria-label*="Send"]'),document.querySelector('button[aria-label*="Gửi"]')].find(b=>b&&!b.disabled&&b.offsetParent!==null);
async function run(t,send=true){t=String(t||'').trim();if(!t)return{ok:false,error:'Prompt rỗng'};let e=null;for(let i=0;i<80&&!e;i++){e=get();if(!e)await sleep(150)}if(!e)return{ok:false,error:'Không tìm thấy ô nhập ChatGPT'};fill(e,t);for(let i=0;i<30;i++){if(val(e)===t)break;await sleep(100)}if(val(e)!==t)return{ok:false,error:'ChatGPT không nhận prompt'};if(send){for(let i=0;i<20;i++){const b=btn();if(b){b.click();return{ok:true}}await sleep(200)}e.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true,cancelable:true}))}return{ok:true}}
chrome.runtime.onMessage.addListener((m,s,reply)=>{if(m?.type==='FILL_AND_SEND_CHATGPT') {run(m.text,m.autoSend!==false).then(reply);return true}});
})();